<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'bitbag_sylius_elasticsearch_plugin.form.type.product_options_filter' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Form/Type/AbstractFilterType.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Form/Type/ProductOptionsFilterType.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Context/ProductOptionsContextInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Context/ProductOptionsContext.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Finder/ProductOptionsFinderInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Finder/ProductOptionsFinder.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/QueryBuilder/QueryBuilderInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/QueryBuilder/ProductOptionsByTaxonQueryBuilder.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/QueryBuilder/HasTaxonQueryBuilder.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Form/Type/ChoiceMapper/ProductOptionsMapperInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Form/Type/ChoiceMapper/ProductOptionsMapper.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyNameResolver/ConcatedNameResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyNameResolver/ConcatedNameResolver.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Formatter/StringFormatterInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Formatter/StringFormatter.php';

return $this->privates['bitbag_sylius_elasticsearch_plugin.form.type.product_options_filter'] = new \BitBag\SyliusElasticsearchPlugin\Form\Type\ProductOptionsFilterType(new \BitBag\SyliusElasticsearchPlugin\Context\ProductOptionsContext(($this->privates['bitbag.sylius_elasticsearch_plugin.context.taxon'] ?? $this->load('getBitbag_SyliusElasticsearchPlugin_Context_TaxonService.php')), new \BitBag\SyliusElasticsearchPlugin\Finder\ProductOptionsFinder(($this->services['fos_elastica.finder.bitbag_option_taxons.default'] ?? $this->load('getFosElastica_Finder_BitbagOptionTaxons_DefaultService.php')), new \BitBag\SyliusElasticsearchPlugin\QueryBuilder\ProductOptionsByTaxonQueryBuilder(new \BitBag\SyliusElasticsearchPlugin\QueryBuilder\HasTaxonQueryBuilder('option_taxons')), 'option_taxons')), ($this->privates['bitbag_sylius_elasticsearch_plugin.property_name_resolver.option'] ?? $this->privates['bitbag_sylius_elasticsearch_plugin.property_name_resolver.option'] = new \BitBag\SyliusElasticsearchPlugin\PropertyNameResolver\ConcatedNameResolver('option')), new \BitBag\SyliusElasticsearchPlugin\Form\Type\ChoiceMapper\ProductOptionsMapper(($this->privates['bitbag.sylius_elasticsearch_plugin.string_formatter'] ?? $this->privates['bitbag.sylius_elasticsearch_plugin.string_formatter'] = new \BitBag\SyliusElasticsearchPlugin\Formatter\StringFormatter())));
