<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'bitbag_sylius_cms_plugin.repository.product' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Product/Repository/ProductRepositoryInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductRepository.php';
include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Repository/ProductRepositoryInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Repository/ProductRepository.php';

$a = ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService());

return $this->services['bitbag_sylius_cms_plugin.repository.product'] = new \BitBag\SyliusCmsPlugin\Repository\ProductRepository($a, $a->getClassMetadata('Sylius\\Component\\Core\\Model\\Product'));
