<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'bitbag_sylius_cms_plugin.controller.helper.form_errors_flash' shared service.

include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Controller/Helper/FormErrorsFlashHelperInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Controller/Helper/FormErrorsFlashHelper.php';

return $this->services['bitbag_sylius_cms_plugin.controller.helper.form_errors_flash'] = new \BitBag\SyliusCmsPlugin\Controller\Helper\FormErrorsFlashHelper(($this->privates['session.flash_bag'] ?? $this->privates['session.flash_bag'] = new \Symfony\Component\HttpFoundation\Session\Flash\FlashBag()), ($this->services['translator'] ?? $this->getTranslatorService()));
