<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'bitbag_sylius_cms_plugin.controller.page_slug' shared service.

include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Controller/PageSlugController.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Product/Generator/SlugGeneratorInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Product/Generator/SlugGenerator.php';

return $this->services['bitbag_sylius_cms_plugin.controller.page_slug'] = new \BitBag\SyliusCmsPlugin\Controller\PageSlugController(($this->services['sylius.generator.slug'] ?? $this->services['sylius.generator.slug'] = new \Sylius\Component\Product\Generator\SlugGenerator()));
