<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'bitbag_sylius_elasticsearch_plugin.property_builder.sold_units' shared service.

include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyBuilder/PropertyBuilderInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyBuilder/AbstractBuilder.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyBuilder/SoldUnitsPropertyBuilder.php';

return $this->privates['bitbag_sylius_elasticsearch_plugin.property_builder.sold_units'] = new \BitBag\SyliusElasticsearchPlugin\PropertyBuilder\SoldUnitsPropertyBuilder(($this->services['sylius.repository.order_item'] ?? $this->load('getSylius_Repository_OrderItemService.php')), 'sold_units');
