<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'bitbag_sylius_cms_plugin.sitemap_provider.section' shared service.

include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Provider/UrlProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/SitemapProvider/SectionUrlProvider.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Factory/SitemapUrlFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Factory/SitemapUrlFactory.php';

return $this->privates['bitbag_sylius_cms_plugin.sitemap_provider.section'] = new \BitBag\SyliusCmsPlugin\SitemapProvider\SectionUrlProvider(($this->services['bitbag_sylius_cms_plugin.repository.section'] ?? $this->load('getBitbagSyliusCmsPlugin_Repository_SectionService.php')), ($this->services['router'] ?? $this->getRouterService()), ($this->privates['sylius.sitemap_url_factory'] ?? $this->privates['sylius.sitemap_url_factory'] = new \SitemapPlugin\Factory\SitemapUrlFactory()), ($this->services['sylius.context.locale'] ?? $this->getSylius_Context_LocaleService()), ($this->services['sylius.context.channel'] ?? $this->getSylius_Context_ChannelService()));
