<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'bitbag_sylius_elasticsearch_plugin.property_builder.option' shared service.

include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyBuilder/PropertyBuilderInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyBuilder/AbstractBuilder.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyBuilder/OptionBuilder.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyNameResolver/ConcatedNameResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyNameResolver/ConcatedNameResolver.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Formatter/StringFormatterInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Formatter/StringFormatter.php';

return $this->privates['bitbag_sylius_elasticsearch_plugin.property_builder.option'] = new \BitBag\SyliusElasticsearchPlugin\PropertyBuilder\OptionBuilder(($this->privates['bitbag_sylius_elasticsearch_plugin.property_name_resolver.option'] ?? $this->privates['bitbag_sylius_elasticsearch_plugin.property_name_resolver.option'] = new \BitBag\SyliusElasticsearchPlugin\PropertyNameResolver\ConcatedNameResolver('option')), ($this->privates['bitbag.sylius_elasticsearch_plugin.string_formatter'] ?? $this->privates['bitbag.sylius_elasticsearch_plugin.string_formatter'] = new \BitBag\SyliusElasticsearchPlugin\Formatter\StringFormatter()));
