<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'bitbag_sylius_cms_plugin.factory.page' shared service.

return $this->services['bitbag_sylius_cms_plugin.factory.page'] = new \Sylius\Component\Resource\Factory\Factory('BitBag\\SyliusCmsPlugin\\Entity\\Page');
