<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'bitbag_sylius_elasticsearch_plugin.form.type.product_attributes_filter' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Form/Type/AbstractFilterType.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Form/Type/ProductAttributesFilterType.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Context/ProductAttributesContextInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Context/ProductAttributesContext.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Finder/ProductAttributesFinderInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Finder/ProductAttributesFinder.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/QueryBuilder/QueryBuilderInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/QueryBuilder/ProductAttributesByTaxonQueryBuilder.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/QueryBuilder/HasTaxonQueryBuilder.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Form/Type/ChoiceMapper/ProductAttributesMapperInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Form/Type/ChoiceMapper/ProductAttributesMapper.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyNameResolver/ConcatedNameResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyNameResolver/ConcatedNameResolver.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Formatter/StringFormatterInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Formatter/StringFormatter.php';

return $this->privates['bitbag_sylius_elasticsearch_plugin.form.type.product_attributes_filter'] = new \BitBag\SyliusElasticsearchPlugin\Form\Type\ProductAttributesFilterType(new \BitBag\SyliusElasticsearchPlugin\Context\ProductAttributesContext(($this->privates['bitbag.sylius_elasticsearch_plugin.context.taxon'] ?? $this->load('getBitbag_SyliusElasticsearchPlugin_Context_TaxonService.php')), new \BitBag\SyliusElasticsearchPlugin\Finder\ProductAttributesFinder(($this->services['fos_elastica.finder.bitbag_attribute_taxons.default'] ?? $this->load('getFosElastica_Finder_BitbagAttributeTaxons_DefaultService.php')), new \BitBag\SyliusElasticsearchPlugin\QueryBuilder\ProductAttributesByTaxonQueryBuilder(new \BitBag\SyliusElasticsearchPlugin\QueryBuilder\HasTaxonQueryBuilder('attribute_taxons')), 'attribute_taxons')), ($this->privates['bitbag_sylius_elasticsearch_plugin.property_name_resolver.attribute'] ?? $this->privates['bitbag_sylius_elasticsearch_plugin.property_name_resolver.attribute'] = new \BitBag\SyliusElasticsearchPlugin\PropertyNameResolver\ConcatedNameResolver('attribute')), new \BitBag\SyliusElasticsearchPlugin\Form\Type\ChoiceMapper\ProductAttributesMapper(($this->services['sylius.repository.product_attribute_value'] ?? $this->load('getSylius_Repository_ProductAttributeValueService.php')), ($this->services['sylius.context.locale'] ?? $this->getSylius_Context_LocaleService()), ($this->privates['bitbag.sylius_elasticsearch_plugin.string_formatter'] ?? $this->privates['bitbag.sylius_elasticsearch_plugin.string_formatter'] = new \BitBag\SyliusElasticsearchPlugin\Formatter\StringFormatter())));
