<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'bitbag_sylius_cms_plugin.assigner.sections' shared service.

include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Assigner/SectionsAssignerInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Assigner/SectionsAssigner.php';

return $this->privates['bitbag_sylius_cms_plugin.assigner.sections'] = new \BitBag\SyliusCmsPlugin\Assigner\SectionsAssigner(($this->services['bitbag_sylius_cms_plugin.repository.section'] ?? $this->load('getBitbagSyliusCmsPlugin_Repository_SectionService.php')));
