<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'bitbag_sylius_elasticsearch_plugin.property_builder.option_taxons' shared service.

include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyBuilder/PropertyBuilderInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyBuilder/AbstractBuilder.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyBuilder/OptionTaxonsBuilder.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/EntityRepository/ProductVariantRepositoryInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/EntityRepository/ProductVariantRepository.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyBuilder/Mapper/ProductTaxonsMapperInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyBuilder/Mapper/ProductTaxonsMapper.php';

return $this->privates['bitbag_sylius_elasticsearch_plugin.property_builder.option_taxons'] = new \BitBag\SyliusElasticsearchPlugin\PropertyBuilder\OptionTaxonsBuilder(($this->services['sylius.repository.product_option_value'] ?? $this->load('getSylius_Repository_ProductOptionValueService.php')), new \BitBag\SyliusElasticsearchPlugin\EntityRepository\ProductVariantRepository(($this->services['sylius.repository.product_variant'] ?? $this->load('getSylius_Repository_ProductVariantService.php'))), ($this->privates['bitbag_sylius_elasticsearch_plugin.property_builder.mapper.product_taxons'] ?? $this->privates['bitbag_sylius_elasticsearch_plugin.property_builder.mapper.product_taxons'] = new \BitBag\SyliusElasticsearchPlugin\PropertyBuilder\Mapper\ProductTaxonsMapper()), 'option', 'option_taxons', array());
