<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'bitbag_sylius_elasticsearch_plugin.form.type.price_filter' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Form/Type/AbstractFilterType.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/Form/Type/PriceFilterType.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyNameResolver/PriceNameResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyNameResolver/PriceNameResolver.php';

return $this->privates['bitbag_sylius_elasticsearch_plugin.form.type.price_filter'] = new \BitBag\SyliusElasticsearchPlugin\Form\Type\PriceFilterType(($this->privates['bitbag_sylius_elasticsearch_plugin.property_name_resolver.price'] ?? $this->privates['bitbag_sylius_elasticsearch_plugin.property_name_resolver.price'] = new \BitBag\SyliusElasticsearchPlugin\PropertyNameResolver\PriceNameResolver('price')));
