<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'bitbag_sylius_elasticsearch_plugin.property_builder.product_taxons' shared service.

include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyBuilder/PropertyBuilderInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyBuilder/AbstractBuilder.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyBuilder/ProductTaxonsBuilder.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyBuilder/Mapper/ProductTaxonsMapperInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/elasticsearch-plugin/src/PropertyBuilder/Mapper/ProductTaxonsMapper.php';

return $this->privates['bitbag_sylius_elasticsearch_plugin.property_builder.product_taxons'] = new \BitBag\SyliusElasticsearchPlugin\PropertyBuilder\ProductTaxonsBuilder(($this->privates['bitbag_sylius_elasticsearch_plugin.property_builder.mapper.product_taxons'] ?? $this->privates['bitbag_sylius_elasticsearch_plugin.property_builder.mapper.product_taxons'] = new \BitBag\SyliusElasticsearchPlugin\PropertyBuilder\Mapper\ProductTaxonsMapper()), 'product_taxons');
