<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.bitbag_sylius_cms_plugin.command.import_from_csv' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Command/ImportFromCsvCommand.php';

return $this->services['console.command.public_alias.bitbag_sylius_cms_plugin.command.import_from_csv'] = new \BitBag\SyliusCmsPlugin\Command\ImportFromCsvCommand(($this->privates['bitbag_sylius_cms_plugin.processor.import'] ?? $this->load('getBitbagSyliusCmsPlugin_Processor_ImportService.php')));
