<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.orm.listeners.resolve_target_entity' shared service.

include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/ResolveTargetEntityListener.php';

$this->privates['doctrine.orm.listeners.resolve_target_entity'] = $instance = new \Doctrine\ORM\Tools\ResolveTargetEntityListener();

$instance->addResolveTargetEntity('Sylius\\Component\\Order\\Model\\OrderInterface', 'Sylius\\Component\\Core\\Model\\Order', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Order\\Model\\OrderItemInterface', 'Sylius\\Component\\Core\\Model\\OrderItem', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Order\\Model\\OrderItemUnitInterface', 'Sylius\\Component\\Core\\Model\\OrderItemUnit', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Order\\Model\\OrderSequenceInterface', 'Sylius\\Component\\Core\\Model\\OrderSequence', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Order\\Model\\AdjustmentInterface', 'Sylius\\Component\\Order\\Model\\Adjustment', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Currency\\Model\\CurrencyInterface', 'Sylius\\Component\\Currency\\Model\\Currency', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Currency\\Model\\ExchangeRateInterface', 'Sylius\\Component\\Currency\\Model\\ExchangeRate', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Locale\\Model\\LocaleInterface', 'Sylius\\Component\\Locale\\Model\\Locale', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Product\\Model\\ProductInterface', 'Sylius\\Component\\Core\\Model\\Product', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Product\\Model\\ProductTranslationInterface', 'Sylius\\Component\\Core\\Model\\ProductTranslation', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Product\\Model\\ProductVariantInterface', 'Sylius\\Component\\Core\\Model\\ProductVariant', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Product\\Model\\ProductVariantTranslationInterface', 'Sylius\\Component\\Product\\Model\\ProductVariantTranslation', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Product\\Model\\ProductOptionInterface', 'Sylius\\Component\\Product\\Model\\ProductOption', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Product\\Model\\ProductOptionTranslationInterface', 'Sylius\\Component\\Product\\Model\\ProductOptionTranslation', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Product\\Model\\ProductAssociationTypeInterface', 'Sylius\\Component\\Product\\Model\\ProductAssociationType', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Product\\Model\\ProductAssociationTypeTranslationInterface', 'Sylius\\Component\\Product\\Model\\ProductAssociationTypeTranslation', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Product\\Model\\ProductOptionValueInterface', 'Sylius\\Component\\Product\\Model\\ProductOptionValue', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Product\\Model\\ProductOptionValueTranslationInterface', 'Sylius\\Component\\Product\\Model\\ProductOptionValueTranslation', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Product\\Model\\ProductAssociationInterface', 'Sylius\\Component\\Product\\Model\\ProductAssociation', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Channel\\Model\\ChannelInterface', 'Sylius\\Component\\Core\\Model\\Channel', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Product\\Model\\ProductAttributeInterface', 'Sylius\\Component\\Product\\Model\\ProductAttribute', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Product\\Model\\ProductAttributeTranslationInterface', 'Sylius\\Component\\Product\\Model\\ProductAttributeTranslation', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Product\\Model\\ProductAttributeValueInterface', 'Sylius\\Component\\Product\\Model\\ProductAttributeValue', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Taxation\\Model\\TaxRateInterface', 'Sylius\\Component\\Core\\Model\\TaxRate', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Taxation\\Model\\TaxCategoryInterface', 'Sylius\\Component\\Taxation\\Model\\TaxCategory', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Shipping\\Model\\ShipmentInterface', 'Sylius\\Component\\Core\\Model\\Shipment', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Shipping\\Model\\ShipmentUnitInterface', 'Sylius\\Component\\Core\\Model\\OrderItemUnit', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Shipping\\Model\\ShippingMethodInterface', 'Sylius\\Component\\Core\\Model\\ShippingMethod', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Shipping\\Model\\ShippingMethodTranslationInterface', 'Sylius\\Component\\Shipping\\Model\\ShippingMethodTranslation', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Shipping\\Model\\ShippingCategoryInterface', 'Sylius\\Component\\Shipping\\Model\\ShippingCategory', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Payment\\Model\\PaymentInterface', 'Sylius\\Component\\Core\\Model\\Payment', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Payment\\Model\\PaymentMethodInterface', 'Sylius\\Component\\Core\\Model\\PaymentMethod', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Payment\\Model\\PaymentMethodTranslationInterface', 'Sylius\\Component\\Payment\\Model\\PaymentMethodTranslation', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Promotion\\Model\\PromotionInterface', 'Sylius\\Component\\Core\\Model\\Promotion', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Promotion\\Model\\PromotionCouponInterface', 'Sylius\\Component\\Core\\Model\\PromotionCoupon', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Promotion\\Model\\PromotionRuleInterface', 'Sylius\\Component\\Promotion\\Model\\PromotionRule', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Promotion\\Model\\PromotionActionInterface', 'Sylius\\Component\\Promotion\\Model\\PromotionAction', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Addressing\\Model\\AddressInterface', 'Sylius\\Component\\Core\\Model\\Address', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Addressing\\Model\\CountryInterface', 'Sylius\\Component\\Addressing\\Model\\Country', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Addressing\\Model\\ProvinceInterface', 'Sylius\\Component\\Addressing\\Model\\Province', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Addressing\\Model\\ZoneInterface', 'Sylius\\Component\\Addressing\\Model\\Zone', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Addressing\\Model\\ZoneMemberInterface', 'Sylius\\Component\\Addressing\\Model\\ZoneMember', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Inventory\\Model\\InventoryUnitInterface', 'Sylius\\Component\\Core\\Model\\OrderItemUnit', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Taxonomy\\Model\\TaxonInterface', 'Sylius\\Component\\Core\\Model\\Taxon', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Taxonomy\\Model\\TaxonTranslationInterface', 'Sylius\\Component\\Taxonomy\\Model\\TaxonTranslation', array());
$instance->addResolveTargetEntity('Sylius\\Component\\User\\Model\\UserInterface', 'Sylius\\Component\\Core\\Model\\ShopUser', array());
$instance->addResolveTargetEntity('Sylius\\Component\\User\\Model\\UserOAuthInterface', 'Sylius\\Component\\User\\Model\\UserOAuth', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Customer\\Model\\CustomerInterface', 'Sylius\\Component\\Core\\Model\\Customer', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Customer\\Model\\CustomerGroupInterface', 'Sylius\\Component\\Customer\\Model\\CustomerGroup', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Review\\Model\\ReviewInterface', 'Sylius\\Component\\Core\\Model\\ProductReview', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Review\\Model\\ReviewerInterface', 'Sylius\\Component\\Core\\Model\\Customer', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Core\\Model\\ProductTaxonInterface', 'Sylius\\Component\\Core\\Model\\ProductTaxon', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Core\\Model\\ProductImageInterface', 'Sylius\\Component\\Core\\Model\\ProductImage', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Core\\Model\\TaxonImageInterface', 'Sylius\\Component\\Core\\Model\\TaxonImage', array());
$instance->addResolveTargetEntity('Sylius\\Component\\Core\\Model\\ChannelPricingInterface', 'Sylius\\Component\\Core\\Model\\ChannelPricing', array());
$instance->addResolveTargetEntity('BitBag\\SyliusCmsPlugin\\Entity\\BlockInterface', 'BitBag\\SyliusCmsPlugin\\Entity\\Block', array());
$instance->addResolveTargetEntity('BitBag\\SyliusCmsPlugin\\Entity\\BlockTranslationInterface', 'BitBag\\SyliusCmsPlugin\\Entity\\BlockTranslation', array());
$instance->addResolveTargetEntity('BitBag\\SyliusCmsPlugin\\Entity\\PageInterface', 'BitBag\\SyliusCmsPlugin\\Entity\\Page', array());
$instance->addResolveTargetEntity('BitBag\\SyliusCmsPlugin\\Entity\\PageTranslationInterface', 'BitBag\\SyliusCmsPlugin\\Entity\\PageTranslation', array());
$instance->addResolveTargetEntity('BitBag\\SyliusCmsPlugin\\Entity\\FrequentlyAskedQuestionInterface', 'BitBag\\SyliusCmsPlugin\\Entity\\FrequentlyAskedQuestion', array());
$instance->addResolveTargetEntity('BitBag\\SyliusCmsPlugin\\Entity\\FrequentlyAskedQuestionTranslationInterface', 'BitBag\\SyliusCmsPlugin\\Entity\\FrequentlyAskedQuestionTranslation', array());
$instance->addResolveTargetEntity('BitBag\\SyliusCmsPlugin\\Entity\\SectionInterface', 'BitBag\\SyliusCmsPlugin\\Entity\\Section', array());
$instance->addResolveTargetEntity('BitBag\\SyliusCmsPlugin\\Entity\\SectionTranslationInterface', 'BitBag\\SyliusCmsPlugin\\Entity\\SectionTranslation', array());
$instance->addResolveTargetEntity('BitBag\\SyliusCmsPlugin\\Entity\\MediaInterface', 'BitBag\\SyliusCmsPlugin\\Entity\\Media', array());
$instance->addResolveTargetEntity('BitBag\\SyliusCmsPlugin\\Entity\\MediaTranslationInterface', 'BitBag\\SyliusCmsPlugin\\Entity\\MediaTranslation', array());
$instance->addResolveTargetEntity('Sylius\\Bundle\\PayumBundle\\Model\\PaymentSecurityTokenInterface', 'Sylius\\Bundle\\PayumBundle\\Model\\PaymentSecurityToken', array());
$instance->addResolveTargetEntity('Sylius\\Bundle\\PayumBundle\\Model\\GatewayConfigInterface', 'Sylius\\Bundle\\PayumBundle\\Model\\GatewayConfig', array());
$instance->addResolveTargetEntity('Sylius\\Bundle\\AdminApiBundle\\Model\\UserInterface', 'Sylius\\Component\\Core\\Model\\AdminUser', array());
$instance->addResolveTargetEntity('Sylius\\Bundle\\AdminApiBundle\\Model\\ClientInterface', 'Sylius\\Bundle\\AdminApiBundle\\Model\\Client', array());
$instance->addResolveTargetEntity('Sylius\\Bundle\\AdminApiBundle\\Model\\AccessTokenInterface', 'Sylius\\Bundle\\AdminApiBundle\\Model\\AccessToken', array());
$instance->addResolveTargetEntity('Sylius\\Bundle\\AdminApiBundle\\Model\\RefreshTokenInterface', 'Sylius\\Bundle\\AdminApiBundle\\Model\\RefreshToken', array());
$instance->addResolveTargetEntity('Sylius\\Bundle\\AdminApiBundle\\Model\\AuthCodeInterface', 'Sylius\\Bundle\\AdminApiBundle\\Model\\AuthCode', array());

return $instance;
