<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_oauth_server.controller.authorize' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/oauth-server-bundle/Controller/AuthorizeController.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/oauth-server-bundle/Form/Handler/AuthorizeFormHandler.php';

$a = ($this->services['request_stack'] ?? $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack());
$b = $this->load('getFosOauthServer_Authorize_FormService.php');

return $this->services['fos_oauth_server.controller.authorize'] = new \FOS\OAuthServerBundle\Controller\AuthorizeController($a, $b, new \FOS\OAuthServerBundle\Form\Handler\AuthorizeFormHandler($b, $a), ($this->privates['fos_oauth_server.server'] ?? $this->load('getFosOauthServer_ServerService.php')), ($this->services['templating'] ?? $this->getTemplatingService()), ($this->services['security.token_storage'] ?? $this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage()), ($this->services['router'] ?? $this->getRouterService()), ($this->services['sylius.oauth_server.client_manager'] ?? $this->load('getSylius_OauthServer_ClientManagerService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['session'] ?? $this->getSessionService()), 'twig');
