<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.index.bitbag_option_taxons' shared service.

include_once $this->targetDirs[3].'/vendor/ruflin/elastica/lib/Elastica/SearchableInterface.php';
include_once $this->targetDirs[3].'/vendor/ruflin/elastica/lib/Elastica/Index.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Elastica/Index.php';

return $this->services['fos_elastica.index.bitbag_option_taxons'] = ($this->services['fos_elastica.client.default'] ?? $this->load('getFosElastica_Client_DefaultService.php'))->getIndex('bitbag_option_taxons_dev');
