<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.finder.bitbag_shop_product.default' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Finder/FinderInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Finder/PaginatedFinderInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Finder/TransformedFinder.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Transformer/ElasticaToModelTransformerInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Transformer/AbstractElasticaToModelTransformer.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/AbstractElasticaToModelTransformer.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/ORM/ElasticaToModelTransformer.php';

$a = new \FOS\ElasticaBundle\Doctrine\ORM\ElasticaToModelTransformer(($this->services['doctrine'] ?? $this->getDoctrineService()), 'Sylius\\Component\\Core\\Model\\Product', array('ignore_missing' => true, 'hints' => array(), 'hydrate' => true, 'query_builder_method' => 'createQueryBuilder', 'identifier' => 'id'));
$a->setPropertyAccessor(($this->privates['fos_elastica.property_accessor'] ?? $this->privates['fos_elastica.property_accessor'] = new \Symfony\Component\PropertyAccess\PropertyAccessor(false, false)));

return $this->services['fos_elastica.finder.bitbag_shop_product.default'] = new \FOS\ElasticaBundle\Finder\TransformedFinder(($this->services['fos_elastica.index.bitbag_shop_product.default'] ?? $this->load('getFosElastica_Index_BitbagShopProduct_DefaultService.php')), $a);
