<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.repository_manager' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Manager/RepositoryManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Manager/RepositoryManager.php';

$this->services['fos_elastica.repository_manager'] = $instance = new \FOS\ElasticaBundle\Manager\RepositoryManager();

$instance->addType('bitbag_shop_product/default', ($this->services['fos_elastica.finder.bitbag_shop_product.default'] ?? $this->load('getFosElastica_Finder_BitbagShopProduct_DefaultService.php')));
$instance->addType('bitbag_option_taxons/default', ($this->services['fos_elastica.finder.bitbag_option_taxons.default'] ?? $this->load('getFosElastica_Finder_BitbagOptionTaxons_DefaultService.php')));
$instance->addType('bitbag_attribute_taxons/default', ($this->services['fos_elastica.finder.bitbag_attribute_taxons.default'] ?? $this->load('getFosElastica_Finder_BitbagAttributeTaxons_DefaultService.php')));

return $instance;
