<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.index.bitbag_attribute_taxons.default' shared service.

include_once $this->targetDirs[3].'/vendor/ruflin/elastica/lib/Elastica/SearchableInterface.php';
include_once $this->targetDirs[3].'/vendor/ruflin/elastica/lib/Elastica/Type.php';

return $this->services['fos_elastica.index.bitbag_attribute_taxons.default'] = ($this->services['fos_elastica.index.bitbag_attribute_taxons'] ?? $this->load('getFosElastica_Index_BitbagAttributeTaxonsService.php'))->getType('default');
