<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.persister_registry' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Persister/PersisterRegistry.php';

$this->services['fos_elastica.persister_registry'] = $instance = new \FOS\ElasticaBundle\Persister\PersisterRegistry(array('bitbag_shop_product' => array('default' => 'fos_elastica.object_persister.bitbag_shop_product.default'), 'bitbag_option_taxons' => array('default' => 'fos_elastica.object_persister.bitbag_option_taxons.default'), 'bitbag_attribute_taxons' => array('default' => 'fos_elastica.object_persister.bitbag_attribute_taxons.default')));

$instance->setContainer($this);

return $instance;
