<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'knp_menu.menu_provider.lazy' shared service.

include_once $this->targetDirs[3].'/vendor/knplabs/knp-menu/src/Knp/Menu/Provider/LazyProvider.php';

return $this->privates['knp_menu.menu_provider.lazy'] = new \Knp\Menu\Provider\LazyProvider(array('sylius.admin.customer.show' => array(0 => function () {
    return ($this->services['sylius.admin.menu_builder.customer.show'] ?? $this->load('getSylius_Admin_MenuBuilder_Customer_ShowService.php'));
}, 1 => 'createMenu'), 'sylius.admin.main' => array(0 => function () {
    return ($this->services['sylius.admin.menu_builder.main'] ?? $this->load('getSylius_Admin_MenuBuilder_MainService.php'));
}, 1 => 'createMenu'), 'sylius.admin.order.show' => array(0 => function () {
    return ($this->services['sylius.admin.menu_builder.order.show'] ?? $this->load('getSylius_Admin_MenuBuilder_Order_ShowService.php'));
}, 1 => 'createMenu'), 'sylius.admin.product_form' => array(0 => function () {
    return ($this->services['sylius.admin.menu_builder.product_form'] ?? $this->load('getSylius_Admin_MenuBuilder_ProductFormService.php'));
}, 1 => 'createMenu'), 'sylius.admin.product_variant_form' => array(0 => function () {
    return ($this->services['sylius.admin.menu_builder.product_variant_form'] ?? $this->load('getSylius_Admin_MenuBuilder_ProductVariantFormService.php'));
}, 1 => 'createMenu'), 'sylius.shop.account' => array(0 => function () {
    return ($this->services['sylius.shop.menu_builder.account'] ?? $this->load('getSylius_Shop_MenuBuilder_AccountService.php'));
}, 1 => 'createMenu')));
