<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.setup.locale' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Installer/Setup/LocaleSetupInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Installer/Setup/LocaleSetup.php';

return $this->services['sylius.setup.locale'] = new \Sylius\Bundle\CoreBundle\Installer\Setup\LocaleSetup(($this->services['sylius.repository.locale'] ?? $this->load('getSylius_Repository_LocaleService.php')), ($this->services['sylius.factory.locale'] ?? $this->services['sylius.factory.locale'] = new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Locale\\Model\\Locale')), 'en_US');
