<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.factory.product_review' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Review/Factory/ReviewFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Review/Factory/ReviewFactory.php';

return $this->services['sylius.factory.product_review'] = new \Sylius\Component\Review\Factory\ReviewFactory(new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Core\\Model\\ProductReview'));
