<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.form.type.api_order' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ResourceBundle/Form/Type/AbstractResourceType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/AdminApiBundle/Form/Type/OrderType.php';

return $this->services['sylius.form.type.api_order'] = new \Sylius\Bundle\AdminApiBundle\Form\Type\OrderType('Sylius\\Component\\Core\\Model\\Order', $this->parameters['sylius.form.type.api_order.validation_groups'], ($this->services['sylius.repository.locale'] ?? $this->load('getSylius_Repository_LocaleService.php')));
