<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.registry.tax_calculation_strategy' shared service.

$this->services['sylius.registry.tax_calculation_strategy'] = $instance = new \Sylius\Component\Registry\PrioritizedServiceRegistry('Sylius\\Component\\Core\\Taxation\\Strategy\\TaxCalculationStrategyInterface', 'Tax calculation strategy');

$instance->register(($this->services['sylius.taxation.order_items_based_strategy'] ?? $this->load('getSylius_Taxation_OrderItemsBasedStrategyService.php')), 0);
$instance->register(($this->services['sylius.taxation.order_item_units_based_strategy'] ?? $this->load('getSylius_Taxation_OrderItemUnitsBasedStrategyService.php')), 0);

return $instance;
