<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.storage.session' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ResourceBundle/Storage/SessionStorage.php';

return $this->services['sylius.storage.session'] = new \Sylius\Bundle\ResourceBundle\Storage\SessionStorage(($this->services['session'] ?? $this->getSessionService()));
