<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.registry.tax_calculator' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Taxation/Calculator/CalculatorInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Taxation/Calculator/DefaultCalculator.php';

$this->services['sylius.registry.tax_calculator'] = $instance = new \Sylius\Component\Registry\ServiceRegistry('Sylius\\Component\\Taxation\\Calculator\\CalculatorInterface', 'Tax calculator');

$instance->register('default', ($this->services['sylius.tax_calculator.default'] ?? $this->services['sylius.tax_calculator.default'] = new \Sylius\Component\Taxation\Calculator\DefaultCalculator()));

return $instance;
