<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.controller.payum' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Controller/PayumController.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Factory/GetStatusFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Factory/GetStatusFactory.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Factory/ResolveNextRouteFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Factory/ResolveNextRouteFactory.php';

return $this->services['sylius.controller.payum'] = new \Sylius\Bundle\PayumBundle\Controller\PayumController(($this->services['payum'] ?? $this->load('getPayumService.php')), ($this->services['sylius.repository.order'] ?? $this->getSylius_Repository_OrderService()), ($this->privates['sylius.resource_registry'] ?? $this->getSylius_ResourceRegistryService())->get("sylius.order"), ($this->privates['sylius.resource_controller.request_configuration_factory'] ?? $this->load('getSylius_ResourceController_RequestConfigurationFactoryService.php')), ($this->privates['sylius.resource_controller.view_handler'] ?? $this->load('getSylius_ResourceController_ViewHandlerService.php')), ($this->services['router'] ?? $this->getRouterService()), ($this->services['sylius.factory.payum_get_status_action'] ?? $this->services['sylius.factory.payum_get_status_action'] = new \Sylius\Bundle\PayumBundle\Factory\GetStatusFactory()), ($this->services['sylius.factory.payum_resolve_next_route'] ?? $this->services['sylius.factory.payum_resolve_next_route'] = new \Sylius\Bundle\PayumBundle\Factory\ResolveNextRouteFactory()));
