<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.factory.add_to_cart_command' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/OrderBundle/Factory/AddToCartCommandFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/OrderBundle/Factory/AddToCartCommandFactory.php';

return $this->services['sylius.factory.add_to_cart_command'] = new \Sylius\Bundle\OrderBundle\Factory\AddToCartCommandFactory();
