<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.commands_provider.database_setup' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProvider.php';

return $this->services['sylius.commands_provider.database_setup'] = new \Sylius\Bundle\CoreBundle\Installer\Provider\DatabaseSetupCommandsProvider(($this->services['doctrine'] ?? $this->getDoctrineService()));
