<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.fixture.example_factory.promotion_rule' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/ExampleFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/AbstractExampleFactory.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/PromotionRuleExampleFactory.php';

return $this->services['sylius.fixture.example_factory.promotion_rule'] = new \Sylius\Bundle\CoreBundle\Fixture\Factory\PromotionRuleExampleFactory(($this->services['sylius.factory.promotion_rule'] ?? $this->load('getSylius_Factory_PromotionRuleService.php')));
