<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.controller.admin.dashboard' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Controller/DashboardController.php';

return $this->services['sylius.controller.admin.dashboard'] = new \Sylius\Bundle\AdminBundle\Controller\DashboardController(($this->services['sylius.dashboard.statistics_provider'] ?? $this->load('getSylius_Dashboard_StatisticsProviderService.php')), ($this->services['sylius.repository.channel'] ?? $this->getSylius_Repository_ChannelService()), ($this->services['templating'] ?? $this->getTemplatingService()), ($this->services['router'] ?? $this->getRouterService()));
