<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.promotion.units_promotion_adjustments_applicator' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Core/Promotion/Applicator/UnitsPromotionAdjustmentsApplicatorInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Core/Promotion/Applicator/UnitsPromotionAdjustmentsApplicator.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Core/Distributor/IntegerDistributorInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Core/Distributor/IntegerDistributor.php';

return $this->services['sylius.promotion.units_promotion_adjustments_applicator'] = new \Sylius\Component\Core\Promotion\Applicator\UnitsPromotionAdjustmentsApplicator(($this->services['sylius.factory.adjustment'] ?? $this->load('getSylius_Factory_AdjustmentService.php')), ($this->services['sylius.integer_distributor'] ?? $this->services['sylius.integer_distributor'] = new \Sylius\Component\Core\Distributor\IntegerDistributor()));
