<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.fixture.example_factory.product_attribute' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/ExampleFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/AbstractExampleFactory.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductAttributeExampleFactory.php';

return $this->services['sylius.fixture.example_factory.product_attribute'] = new \Sylius\Bundle\CoreBundle\Fixture\Factory\ProductAttributeExampleFactory(($this->services['sylius.factory.product_attribute'] ?? $this->load('getSylius_Factory_ProductAttributeService.php')), ($this->services['sylius.repository.locale'] ?? $this->load('getSylius_Repository_LocaleService.php')), $this->parameters['sylius.attribute.attribute_types']);
