<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.security.password_encoder' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/User/Security/UserPasswordEncoderInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/UserBundle/Security/UserPasswordEncoder.php';

return $this->services['sylius.security.password_encoder'] = new \Sylius\Bundle\UserBundle\Security\UserPasswordEncoder(($this->privates['security.encoder_factory.generic'] ?? $this->load('getSecurity_EncoderFactory_GenericService.php')));
