<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.invoice_number_generator' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Core/Payment/InvoiceNumberGeneratorInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Core/Payment/IdBasedInvoiceNumberGenerator.php';

return $this->services['sylius.invoice_number_generator'] = new \Sylius\Component\Core\Payment\IdBasedInvoiceNumberGenerator();
