<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.resource_controller.resources_collection_provider' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ResourceBundle/Controller/ResourcesCollectionProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ResourceBundle/Controller/ResourcesCollectionProvider.php';
include_once $this->targetDirs[3].'/vendor/willdurand/hateoas/src/Hateoas/Representation/Factory/PagerfantaFactory.php';

return $this->privates['sylius.resource_controller.resources_collection_provider'] = new \Sylius\Bundle\ResourceBundle\Controller\ResourcesCollectionProvider(($this->services['sylius.resource_controller.resources_resolver.grid_aware'] ?? $this->load('getSylius_ResourceController_ResourcesResolver_GridAwareService.php')), new \Hateoas\Representation\Factory\PagerfantaFactory());
