<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.order_payment_provider' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Core/Payment/Provider/OrderPaymentProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Core/Payment/Provider/OrderPaymentProvider.php';

return $this->services['sylius.order_payment_provider'] = new \Sylius\Component\Core\Payment\Provider\OrderPaymentProvider(($this->services['sylius.payment_method_resolver.default'] ?? $this->load('getSylius_PaymentMethodResolver_DefaultService.php')), ($this->services['sylius.factory.payment'] ?? $this->load('getSylius_Factory_PaymentService.php')), ($this->services['sm.factory'] ?? $this->getSm_FactoryService()));
