<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.admin.menu_builder.product_variant_form' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Menu/ProductVariantFormMenuBuilder.php';

return $this->services['sylius.admin.menu_builder.product_variant_form'] = new \Sylius\Bundle\AdminBundle\Menu\ProductVariantFormMenuBuilder(($this->services['knp_menu.factory'] ?? $this->load('getKnpMenu_FactoryService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
