<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.controller.customer_statistics' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Controller/CustomerStatisticsController.php';

return $this->services['sylius.controller.customer_statistics'] = new \Sylius\Bundle\AdminBundle\Controller\CustomerStatisticsController(($this->services['sylius.customer_statistics_provider'] ?? $this->load('getSylius_CustomerStatisticsProviderService.php')), ($this->services['sylius.repository.customer'] ?? $this->load('getSylius_Repository_CustomerService.php')), ($this->services['templating'] ?? $this->getTemplatingService()));
