<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.email_sender' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Mailer/Sender/SenderInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Mailer/Sender/Sender.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Mailer/Provider/DefaultSettingsProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Mailer/Provider/DefaultSettingsProvider.php';

return $this->services['sylius.email_sender'] = new \Sylius\Component\Mailer\Sender\Sender(($this->services['sylius.email_renderer.adapter.twig'] ?? $this->load('getSylius_EmailRenderer_Adapter_TwigService.php')), ($this->services['sylius.email_sender.adapter.swiftmailer'] ?? $this->load('getSylius_EmailSender_Adapter_SwiftmailerService.php')), ($this->services['sylius.email_provider'] ?? $this->load('getSylius_EmailProviderService.php')), ($this->services['sylius.mailer.default_settings_provider'] ?? $this->services['sylius.mailer.default_settings_provider'] = new \Sylius\Component\Mailer\Provider\DefaultSettingsProvider('Example.com', 'no-reply@example.com')));
