<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.listener.order_customer_ip' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/EventListener/OrderCustomerIpListener.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Assigner/IpAssignerInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Assigner/CustomerIpAssigner.php';

return $this->services['sylius.listener.order_customer_ip'] = new \Sylius\Bundle\ShopBundle\EventListener\OrderCustomerIpListener(($this->services['sylius.customer_ip_assigner'] ?? $this->services['sylius.customer_ip_assigner'] = new \Sylius\Bundle\CoreBundle\Assigner\CustomerIpAssigner()), ($this->services['request_stack'] ?? $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));
