<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.listener.shipment_ship' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/EventListener/ShipmentShipListener.php';

return $this->services['sylius.listener.shipment_ship'] = new \Sylius\Bundle\AdminBundle\EventListener\ShipmentShipListener(($this->services['sylius.email_manager.shipment'] ?? $this->load('getSylius_EmailManager_ShipmentService.php')));
