<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.unpaid_orders_state_updater' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Core/Updater/UnpaidOrdersStateUpdaterInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Core/Updater/UnpaidOrdersStateUpdater.php';

return $this->services['sylius.unpaid_orders_state_updater'] = new \Sylius\Component\Core\Updater\UnpaidOrdersStateUpdater(($this->services['sylius.repository.order'] ?? $this->getSylius_Repository_OrderService()), ($this->services['sm.factory'] ?? $this->getSm_FactoryService()), '5 days');
