<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.listener.review_create' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/EventListener/ReviewCreateListener.php';

return $this->services['sylius.listener.review_create'] = new \Sylius\Bundle\CoreBundle\EventListener\ReviewCreateListener(($this->services['sylius.context.customer'] ?? $this->getSylius_Context_CustomerService()));
