<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.installer.checker.sylius_requirements' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Installer/Checker/RequirementsCheckerInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Installer/Checker/SyliusRequirementsChecker.php';

return $this->services['sylius.installer.checker.sylius_requirements'] = new \Sylius\Bundle\CoreBundle\Installer\Checker\SyliusRequirementsChecker(($this->services['sylius.requirements'] ?? $this->load('getSylius_RequirementsService.php')));
