<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.form.event_subscriber.product_variant_generator' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ProductBundle/Form/EventSubscriber/GenerateProductVariantsSubscriber.php';

return $this->services['sylius.form.event_subscriber.product_variant_generator'] = new \Sylius\Bundle\ProductBundle\Form\EventSubscriber\GenerateProductVariantsSubscriber(($this->services['sylius.generator.product_variant'] ?? $this->load('getSylius_Generator_ProductVariantService.php')));
