<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.factory.payum_get_status_action' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Factory/GetStatusFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Factory/GetStatusFactory.php';

return $this->services['sylius.factory.payum_get_status_action'] = new \Sylius\Bundle\PayumBundle\Factory\GetStatusFactory();
