<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.factory.payment' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Payment/Factory/PaymentFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Payment/Factory/PaymentFactory.php';

return $this->services['sylius.factory.payment'] = new \Sylius\Component\Payment\Factory\PaymentFactory(new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Core\\Model\\Payment'));
