<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.admin_user.token_generator.email_verification' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/User/Security/Generator/GeneratorInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/User/Security/Generator/UniqueTokenGenerator.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/User/Security/Checker/UniquenessCheckerInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/User/Security/Checker/TokenUniquenessChecker.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Resource/Generator/RandomnessGeneratorInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Resource/Generator/RandomnessGenerator.php';

return $this->services['sylius.admin_user.token_generator.email_verification'] = new \Sylius\Component\User\Security\Generator\UniqueTokenGenerator(($this->services['sylius.random_generator'] ?? $this->services['sylius.random_generator'] = new \Sylius\Component\Resource\Generator\RandomnessGenerator()), new \Sylius\Component\User\Security\Checker\TokenUniquenessChecker(($this->services['sylius.repository.admin_user'] ?? $this->load('getSylius_Repository_AdminUserService.php')), 'emailVerificationToken'), 16);
