<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.factory.tax_category' shared service.

return $this->services['sylius.factory.tax_category'] = new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Taxation\\Model\\TaxCategory');
