<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.promotion_action.shipping_percentage_discount' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Promotion/Action/PromotionActionCommandInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Core/Promotion/Action/ShippingPercentageDiscountPromotionActionCommand.php';

return $this->services['sylius.promotion_action.shipping_percentage_discount'] = new \Sylius\Component\Core\Promotion\Action\ShippingPercentageDiscountPromotionActionCommand(($this->services['sylius.factory.adjustment'] ?? $this->load('getSylius_Factory_AdjustmentService.php')));
