<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.sitemap_builder' shared service.

include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Builder/BuilderInterface.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Builder/SitemapBuilderInterface.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Builder/SitemapBuilder.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Factory/SitemapFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Factory/SitemapFactory.php';

$this->privates['sylius.sitemap_builder'] = $instance = new \SitemapPlugin\Builder\SitemapBuilder(new \SitemapPlugin\Factory\SitemapFactory());

$instance->addProvider(($this->privates['bitbag_sylius_cms_plugin.sitemap_provider.page'] ?? $this->load('getBitbagSyliusCmsPlugin_SitemapProvider_PageService.php')));
$instance->addProvider(($this->privates['bitbag_sylius_cms_plugin.sitemap_provider.section'] ?? $this->load('getBitbagSyliusCmsPlugin_SitemapProvider_SectionService.php')));
$instance->addProvider(($this->privates['sylius.sitemap_provider.product'] ?? $this->load('getSylius_SitemapProvider_ProductService.php')));
$instance->addProvider(($this->privates['sylius.sitemap_provider.taxon'] ?? $this->load('getSylius_SitemapProvider_TaxonService.php')));
$instance->addProvider(($this->privates['sylius.sitemap_provider.static'] ?? $this->load('getSylius_SitemapProvider_StaticService.php')));

return $instance;
