<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.form.event_subscriber.build_promotion_rule' shared service.

return $this->services['sylius.form.event_subscriber.build_promotion_rule'] = new \Sylius\Bundle\CoreBundle\Form\EventSubscriber\BuildChannelBasedPromotionRuleFormSubscriber(($this->services['sylius.registry_promotion_rule_checker'] ?? $this->load('getSylius_RegistryPromotionRuleCheckerService.php')), ($this->services['form.factory'] ?? $this->getForm_FactoryService()), ($this->services['sylius.repository.channel'] ?? $this->getSylius_Repository_ChannelService()));
