<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.email_manager.contact' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/EmailManager/ContactEmailManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/EmailManager/ContactEmailManager.php';

return $this->services['sylius.email_manager.contact'] = new \Sylius\Bundle\ShopBundle\EmailManager\ContactEmailManager(($this->services['sylius.email_sender'] ?? $this->load('getSylius_EmailSenderService.php')));
