<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.form.type.gateway_config' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ResourceBundle/Form/Type/AbstractResourceType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Form/Type/GatewayConfigType.php';

return $this->services['sylius.form.type.gateway_config'] = new \Sylius\Bundle\PayumBundle\Form\Type\GatewayConfigType('Sylius\\Bundle\\PayumBundle\\Model\\GatewayConfig', $this->parameters['sylius.form.type.gateway_config.validation_groups'], ($this->services['sylius.form_registry.payum_gateway_config'] ?? $this->load('getSylius_FormRegistry_PayumGatewayConfigService.php')));
