<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.sequential_order_number_generator' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/OrderBundle/NumberGenerator/OrderNumberGeneratorInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Order/NumberGenerator/SequentialOrderNumberGenerator.php';

return $this->services['sylius.sequential_order_number_generator'] = new \Sylius\Bundle\CoreBundle\Order\NumberGenerator\SequentialOrderNumberGenerator(($this->services['sylius.repository.order_sequence'] ?? $this->load('getSylius_Repository_OrderSequenceService.php')), ($this->services['sylius.factory.order_sequence'] ?? $this->services['sylius.factory.order_sequence'] = new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Core\\Model\\OrderSequence')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
