<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylus.payum_action.offline.status' shared service.

include_once $this->targetDirs[3].'/vendor/payum/payum/src/Payum/Core/Action/ActionInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Action/Offline/StatusAction.php';

return $this->services['sylus.payum_action.offline.status'] = new \Sylius\Bundle\PayumBundle\Action\Offline\StatusAction();
