<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.console.command.resource_debug' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ResourceBundle/Command/DebugResourceCommand.php';

return $this->services['sylius.console.command.resource_debug'] = new \Sylius\Bundle\ResourceBundle\Command\DebugResourceCommand(($this->privates['sylius.resource_registry'] ?? $this->getSylius_ResourceRegistryService()));
