<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.order_number_assigner' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/OrderBundle/NumberAssigner/OrderNumberAssignerInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/OrderBundle/NumberAssigner/OrderNumberAssigner.php';

return $this->services['sylius.order_number_assigner'] = new \Sylius\Bundle\OrderBundle\NumberAssigner\OrderNumberAssigner(($this->services['sylius.sequential_order_number_generator'] ?? $this->load('getSylius_SequentialOrderNumberGeneratorService.php')));
