<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.listener.product_review_change' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ReviewBundle/EventListener/ReviewChangeListener.php';

return $this->services['sylius.listener.product_review_change'] = new \Sylius\Bundle\ReviewBundle\EventListener\ReviewChangeListener(($this->services['sylius.product_review.average_rating_updater'] ?? $this->load('getSylius_ProductReview_AverageRatingUpdaterService.php')));
