<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.listener.password_updater' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/UserBundle/EventListener/PasswordUpdaterListener.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/EventListener/PasswordUpdaterListener.php';

return $this->services['sylius.listener.password_updater'] = new \Sylius\Bundle\CoreBundle\EventListener\PasswordUpdaterListener(($this->services['sylius.security.password_updater'] ?? $this->load('getSylius_Security_PasswordUpdaterService.php')));
