<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.listener.order_promotion_integrity_checker' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/EventListener/OrderPromotionIntegrityChecker.php';

return $this->services['sylius.listener.order_promotion_integrity_checker'] = new \Sylius\Bundle\ShopBundle\EventListener\OrderPromotionIntegrityChecker(($this->services['sylius.promotion_eligibility_checker'] ?? $this->load('getSylius_PromotionEligibilityCheckerService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['router'] ?? $this->getRouterService()));
