<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.listener.canonicalizer' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/EventListener/CanonicalizerListener.php';

return $this->services['sylius.listener.canonicalizer'] = new \Sylius\Bundle\CoreBundle\EventListener\CanonicalizerListener(($this->services['sylius.canonicalizer'] ?? $this->services['sylius.canonicalizer'] = new \Sylius\Component\User\Canonicalizer\Canonicalizer()));
