<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.factory.product_attribute' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/Factory/AttributeFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/Factory/AttributeFactory.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Resource/Factory/TranslatableFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Resource/Factory/TranslatableFactory.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/AttributeType/AttributeTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/AttributeType/TextAttributeType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/AttributeType/TextareaAttributeType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/AttributeType/CheckboxAttributeType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/AttributeType/IntegerAttributeType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/AttributeType/PercentAttributeType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/AttributeType/DatetimeAttributeType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/AttributeType/DateAttributeType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/AttributeType/SelectAttributeType.php';

$a = new \Sylius\Component\Registry\ServiceRegistry('Sylius\\Component\\Attribute\\AttributeType\\AttributeTypeInterface', 'attribute type');
$a->register('text', ($this->services['sylius.attribute_type.text'] ?? $this->services['sylius.attribute_type.text'] = new \Sylius\Component\Attribute\AttributeType\TextAttributeType()));
$a->register('textarea', ($this->services['sylius.attribute_type.textarea'] ?? $this->services['sylius.attribute_type.textarea'] = new \Sylius\Component\Attribute\AttributeType\TextareaAttributeType()));
$a->register('checkbox', ($this->services['sylius.attribute_type.checkbox'] ?? $this->services['sylius.attribute_type.checkbox'] = new \Sylius\Component\Attribute\AttributeType\CheckboxAttributeType()));
$a->register('integer', ($this->services['sylius.attribute_type.integer'] ?? $this->services['sylius.attribute_type.integer'] = new \Sylius\Component\Attribute\AttributeType\IntegerAttributeType()));
$a->register('percent', ($this->services['sylius.attribute_type.percent'] ?? $this->services['sylius.attribute_type.percent'] = new \Sylius\Component\Attribute\AttributeType\PercentAttributeType()));
$a->register('datetime', ($this->services['sylius.attribute_type.datetime'] ?? $this->services['sylius.attribute_type.datetime'] = new \Sylius\Component\Attribute\AttributeType\DatetimeAttributeType()));
$a->register('date', ($this->services['sylius.attribute_type.date'] ?? $this->services['sylius.attribute_type.date'] = new \Sylius\Component\Attribute\AttributeType\DateAttributeType()));
$a->register('select', ($this->services['sylius.attribute_type.select'] ?? $this->services['sylius.attribute_type.select'] = new \Sylius\Component\Attribute\AttributeType\SelectAttributeType()));

return $this->services['sylius.factory.product_attribute'] = new \Sylius\Component\Attribute\Factory\AttributeFactory(new \Sylius\Component\Resource\Factory\TranslatableFactory(new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Product\\Model\\ProductAttribute'), ($this->services['sylius.translation_locale_provider.admin'] ?? $this->load('getSylius_TranslationLocaleProvider_AdminService.php'))), $a);
