<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.customer_unique_address_adder' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Core/Customer/CustomerAddressAdderInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Core/Customer/CustomerUniqueAddressAdder.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Addressing/Comparator/AddressComparatorInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Addressing/Comparator/AddressComparator.php';

return $this->services['sylius.customer_unique_address_adder'] = new \Sylius\Component\Core\Customer\CustomerUniqueAddressAdder(($this->services['sylius.address_comparator'] ?? $this->services['sylius.address_comparator'] = new \Sylius\Component\Addressing\Comparator\AddressComparator()));
