<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.factory.gateway_config' shared service.

return $this->services['sylius.factory.gateway_config'] = new \Sylius\Component\Resource\Factory\Factory('Sylius\\Bundle\\PayumBundle\\Model\\GatewayConfig');
