<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.validator.promotion_subject_coupon' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Validator/ConstraintValidatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Validator/ConstraintValidator.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/PromotionBundle/Validator/PromotionSubjectCouponValidator.php';

return $this->services['sylius.validator.promotion_subject_coupon'] = new \Sylius\Bundle\PromotionBundle\Validator\PromotionSubjectCouponValidator(($this->services['sylius.promotion_eligibility_checker'] ?? $this->load('getSylius_PromotionEligibilityCheckerService.php')));
