<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.fixture.locale' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/FixturesBundle/Fixture/FixtureInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/FixturesBundle/Fixture/AbstractFixture.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/LocaleFixture.php';

return $this->services['sylius.fixture.locale'] = new \Sylius\Bundle\CoreBundle\Fixture\LocaleFixture(($this->services['sylius.factory.locale'] ?? $this->services['sylius.factory.locale'] = new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Locale\\Model\\Locale')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), 'en_US');
