<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.fixture.example_factory.tax_rate' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/ExampleFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/AbstractExampleFactory.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxRateExampleFactory.php';

return $this->services['sylius.fixture.example_factory.tax_rate'] = new \Sylius\Bundle\CoreBundle\Fixture\Factory\TaxRateExampleFactory(($this->services['sylius.factory.tax_rate'] ?? $this->services['sylius.factory.tax_rate'] = new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Core\\Model\\TaxRate')), ($this->services['sylius.repository.zone'] ?? $this->getSylius_Repository_ZoneService()), ($this->services['sylius.repository.tax_category'] ?? $this->load('getSylius_Repository_TaxCategoryService.php')));
