<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.factory.zone' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Addressing/Factory/ZoneFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Addressing/Factory/ZoneFactory.php';

return $this->services['sylius.factory.zone'] = new \Sylius\Component\Addressing\Factory\ZoneFactory(new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Addressing\\Model\\Zone'), ($this->services['sylius.factory.zone_member'] ?? $this->services['sylius.factory.zone_member'] = new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Addressing\\Model\\ZoneMember')));
