<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.listener.select_product_attribute_choice_remove' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ProductBundle/EventListener/SelectProductAttributeChoiceRemoveListener.php';

return $this->services['sylius.listener.select_product_attribute_choice_remove'] = new \Sylius\Bundle\ProductBundle\EventListener\SelectProductAttributeChoiceRemoveListener('Sylius\\Component\\Product\\Model\\ProductAttributeValue');
