<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.fixture.example_factory.admin_user' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/ExampleFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/AbstractExampleFactory.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/AdminUserExampleFactory.php';

return $this->services['sylius.fixture.example_factory.admin_user'] = new \Sylius\Bundle\CoreBundle\Fixture\Factory\AdminUserExampleFactory(($this->services['sylius.factory.admin_user'] ?? $this->services['sylius.factory.admin_user'] = new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Core\\Model\\AdminUser')), 'en_US');
