<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.factory.exchange_rate' shared service.

return $this->services['sylius.factory.exchange_rate'] = new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Currency\\Model\\ExchangeRate');
