<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.registry.attribute_type' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/AttributeType/AttributeTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/AttributeType/TextAttributeType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/AttributeType/TextareaAttributeType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/AttributeType/CheckboxAttributeType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/AttributeType/IntegerAttributeType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/AttributeType/PercentAttributeType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/AttributeType/DatetimeAttributeType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/AttributeType/DateAttributeType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Attribute/AttributeType/SelectAttributeType.php';

$this->services['sylius.registry.attribute_type'] = $instance = new \Sylius\Component\Registry\ServiceRegistry('Sylius\\Component\\Attribute\\AttributeType\\AttributeTypeInterface', 'attribute type');

$instance->register('text', ($this->services['sylius.attribute_type.text'] ?? $this->services['sylius.attribute_type.text'] = new \Sylius\Component\Attribute\AttributeType\TextAttributeType()));
$instance->register('textarea', ($this->services['sylius.attribute_type.textarea'] ?? $this->services['sylius.attribute_type.textarea'] = new \Sylius\Component\Attribute\AttributeType\TextareaAttributeType()));
$instance->register('checkbox', ($this->services['sylius.attribute_type.checkbox'] ?? $this->services['sylius.attribute_type.checkbox'] = new \Sylius\Component\Attribute\AttributeType\CheckboxAttributeType()));
$instance->register('integer', ($this->services['sylius.attribute_type.integer'] ?? $this->services['sylius.attribute_type.integer'] = new \Sylius\Component\Attribute\AttributeType\IntegerAttributeType()));
$instance->register('percent', ($this->services['sylius.attribute_type.percent'] ?? $this->services['sylius.attribute_type.percent'] = new \Sylius\Component\Attribute\AttributeType\PercentAttributeType()));
$instance->register('datetime', ($this->services['sylius.attribute_type.datetime'] ?? $this->services['sylius.attribute_type.datetime'] = new \Sylius\Component\Attribute\AttributeType\DatetimeAttributeType()));
$instance->register('date', ($this->services['sylius.attribute_type.date'] ?? $this->services['sylius.attribute_type.date'] = new \Sylius\Component\Attribute\AttributeType\DateAttributeType()));
$instance->register('select', ($this->services['sylius.attribute_type.select'] ?? $this->services['sylius.attribute_type.select'] = new \Sylius\Component\Attribute\AttributeType\SelectAttributeType()));

return $instance;
