<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.order_processing.shipping_charges_processor' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Order/Processor/OrderProcessorInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Core/OrderProcessing/ShippingChargesProcessor.php';

return $this->services['sylius.order_processing.shipping_charges_processor'] = new \Sylius\Component\Core\OrderProcessing\ShippingChargesProcessor(($this->services['sylius.factory.adjustment'] ?? $this->load('getSylius_Factory_AdjustmentService.php')), ($this->services['sylius.shipping_calculator'] ?? $this->load('getSylius_ShippingCalculatorService.php')));
