<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.factory.payum_resolve_next_route' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Factory/ResolveNextRouteFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Factory/ResolveNextRouteFactory.php';

return $this->services['sylius.factory.payum_resolve_next_route'] = new \Sylius\Bundle\PayumBundle\Factory\ResolveNextRouteFactory();
