<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.resource_controller.view_handler' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ResourceBundle/Controller/ViewHandlerInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ResourceBundle/Controller/ViewHandler.php';

return $this->privates['sylius.resource_controller.view_handler'] = new \Sylius\Bundle\ResourceBundle\Controller\ViewHandler(($this->services['fos_rest.view_handler'] ?? $this->load('getFosRest_ViewHandlerService.php')));
