<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.expired_carts_remover' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Order/Remover/ExpiredCartsRemoverInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/OrderBundle/Remover/ExpiredCartsRemover.php';

return $this->services['sylius.expired_carts_remover'] = new \Sylius\Bundle\OrderBundle\Remover\ExpiredCartsRemover(($this->services['sylius.repository.order'] ?? $this->getSylius_Repository_OrderService()), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), '2 days');
