<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.form.type.cart_item' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ResourceBundle/Form/Type/AbstractResourceType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/OrderBundle/Form/Type/CartItemType.php';

return $this->services['sylius.form.type.cart_item'] = new \Sylius\Bundle\OrderBundle\Form\Type\CartItemType('Sylius\\Component\\Core\\Model\\OrderItem', $this->parameters['sylius.form.type.cart_item.validation_groups'], ($this->services['sylius.form.data_mapper.order_item_quantity'] ?? $this->load('getSylius_Form_DataMapper_OrderItemQuantityService.php')));
