<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.controller.shop.contact' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Controller/ContactController.php';

return $this->services['sylius.controller.shop.contact'] = new \Sylius\Bundle\ShopBundle\Controller\ContactController(($this->services['router'] ?? $this->getRouterService()), ($this->services['form.factory'] ?? $this->getForm_FactoryService()), ($this->services['templating'] ?? $this->getTemplatingService()), ($this->services['sylius.context.channel'] ?? $this->getSylius_Context_ChannelService()), ($this->services['sylius.context.customer'] ?? $this->getSylius_Context_CustomerService()), ($this->services['sylius.email_manager.contact'] ?? $this->load('getSylius_EmailManager_ContactService.php')));
