<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.currency_name_converter' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Currency/Converter/CurrencyNameConverterInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Currency/Converter/CurrencyNameConverter.php';

return $this->services['sylius.currency_name_converter'] = new \Sylius\Component\Currency\Converter\CurrencyNameConverter();
