<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.form.type.product_attribute_value' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ResourceBundle/Form/Type/AbstractResourceType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeValueType.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ProductBundle/Form/Type/ProductAttributeValueType.php';

return $this->services['sylius.form.type.product_attribute_value'] = new \Sylius\Bundle\ProductBundle\Form\Type\ProductAttributeValueType('Sylius\\Component\\Product\\Model\\ProductAttributeValue', $this->parameters['sylius.form.type.product_attribute_value.validation_groups'], 'Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductAttributeChoiceType', ($this->services['sylius.repository.product_attribute'] ?? $this->load('getSylius_Repository_ProductAttributeService.php')), ($this->services['sylius.repository.locale'] ?? $this->load('getSylius_Repository_LocaleService.php')), ($this->services['sylius.form_registry.attribute_type'] ?? $this->load('getSylius_FormRegistry_AttributeTypeService.php')));
