<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.listener.shop_user_last_login' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/UserBundle/EventListener/UserLastLoginSubscriber.php';

return $this->privates['sylius.listener.shop_user_last_login'] = new \Sylius\Bundle\UserBundle\EventListener\UserLastLoginSubscriber(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), 'Sylius\\Component\\Core\\Model\\ShopUser');
