<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.controller.taxon_slug' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/TaxonomyBundle/Controller/TaxonSlugController.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Taxonomy/Generator/TaxonSlugGeneratorInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Taxonomy/Generator/TaxonSlugGenerator.php';

return $this->services['sylius.controller.taxon_slug'] = new \Sylius\Bundle\TaxonomyBundle\Controller\TaxonSlugController(($this->services['sylius.generator.taxon_slug'] ?? $this->services['sylius.generator.taxon_slug'] = new \Sylius\Component\Taxonomy\Generator\TaxonSlugGenerator()), ($this->services['sylius.repository.taxon'] ?? $this->load('getSylius_Repository_TaxonService.php')), ($this->services['sylius.factory.taxon'] ?? $this->load('getSylius_Factory_TaxonService.php')));
