<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.customer_ip_assigner' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Assigner/IpAssignerInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Assigner/CustomerIpAssigner.php';

return $this->services['sylius.customer_ip_assigner'] = new \Sylius\Bundle\CoreBundle\Assigner\CustomerIpAssigner();
