<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius_fixtures.fixture_registry' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/FixturesBundle/Fixture/FixtureRegistryInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/FixturesBundle/Fixture/FixtureRegistry.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/FixturesBundle/Fixture/FixtureInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/FixturesBundle/Fixture/AbstractFixture.php';
include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Fixture/BlockFixture.php';
include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Fixture/Factory/FixtureFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Fixture/Factory/BlockFixtureFactory.php';
include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Fixture/PageFixture.php';
include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Fixture/Factory/PageFixtureFactory.php';
include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Fixture/FrequentlyAskedQuestionFixture.php';
include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Fixture/Factory/FrequentlyAskedQuestionFixtureFactory.php';
include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Fixture/SectionFixture.php';
include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Fixture/Factory/SectionFixtureFactory.php';
include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Fixture/MediaFixture.php';
include_once $this->targetDirs[3].'/vendor/bitbag/cms-plugin/src/Fixture/Factory/MediaFixtureFactory.php';

$this->services['sylius_fixtures.fixture_registry'] = $instance = new \Sylius\Bundle\FixturesBundle\Fixture\FixtureRegistry();

$a = ($this->services['bitbag_sylius_cms_plugin.repository.section'] ?? $this->load('getBitbagSyliusCmsPlugin_Repository_SectionService.php'));
$b = ($this->services['sylius.repository.product'] ?? $this->load('getSylius_Repository_ProductService.php'));
$c = ($this->services['sylius.context.channel'] ?? $this->getSylius_Context_ChannelService());
$d = ($this->services['sylius.context.locale'] ?? $this->getSylius_Context_LocaleService());

$instance->addFixture(new \BitBag\SyliusCmsPlugin\Fixture\BlockFixture(new \BitBag\SyliusCmsPlugin\Fixture\Factory\BlockFixtureFactory(($this->services['bitbag_sylius_cms_plugin.factory.block'] ?? $this->services['bitbag_sylius_cms_plugin.factory.block'] = new \Sylius\Component\Resource\Factory\Factory('BitBag\\SyliusCmsPlugin\\Entity\\Block')), ($this->services['bitbag_sylius_cms_plugin.factory.block_translation'] ?? $this->services['bitbag_sylius_cms_plugin.factory.block_translation'] = new \Sylius\Component\Resource\Factory\Factory('BitBag\\SyliusCmsPlugin\\Entity\\BlockTranslation')), ($this->services['bitbag_sylius_cms_plugin.repository.block'] ?? $this->getBitbagSyliusCmsPlugin_Repository_BlockService()), $a, $b, $c, $d)));
$instance->addFixture(new \BitBag\SyliusCmsPlugin\Fixture\PageFixture(new \BitBag\SyliusCmsPlugin\Fixture\Factory\PageFixtureFactory(($this->services['bitbag_sylius_cms_plugin.factory.page'] ?? $this->services['bitbag_sylius_cms_plugin.factory.page'] = new \Sylius\Component\Resource\Factory\Factory('BitBag\\SyliusCmsPlugin\\Entity\\Page')), ($this->services['bitbag_sylius_cms_plugin.factory.page_translation'] ?? $this->services['bitbag_sylius_cms_plugin.factory.page_translation'] = new \Sylius\Component\Resource\Factory\Factory('BitBag\\SyliusCmsPlugin\\Entity\\PageTranslation')), ($this->services['bitbag_sylius_cms_plugin.repository.page'] ?? $this->getBitbagSyliusCmsPlugin_Repository_PageService()), $a, ($this->services['sylius.image_uploader'] ?? $this->load('getSylius_ImageUploaderService.php')), $b, $c, $d)));
$instance->addFixture(new \BitBag\SyliusCmsPlugin\Fixture\FrequentlyAskedQuestionFixture(new \BitBag\SyliusCmsPlugin\Fixture\Factory\FrequentlyAskedQuestionFixtureFactory(($this->services['bitbag_sylius_cms_plugin.factory.frequently_asked_question'] ?? $this->services['bitbag_sylius_cms_plugin.factory.frequently_asked_question'] = new \Sylius\Component\Resource\Factory\Factory('BitBag\\SyliusCmsPlugin\\Entity\\FrequentlyAskedQuestion')), ($this->services['bitbag_sylius_cms_plugin.factory.frequently_asked_question_translation'] ?? $this->services['bitbag_sylius_cms_plugin.factory.frequently_asked_question_translation'] = new \Sylius\Component\Resource\Factory\Factory('BitBag\\SyliusCmsPlugin\\Entity\\FrequentlyAskedQuestionTranslation')), ($this->services['bitbag_sylius_cms_plugin.repository.frequently_asked_question'] ?? $this->load('getBitbagSyliusCmsPlugin_Repository_FrequentlyAskedQuestionService.php')), $c)));
$instance->addFixture(new \BitBag\SyliusCmsPlugin\Fixture\SectionFixture(new \BitBag\SyliusCmsPlugin\Fixture\Factory\SectionFixtureFactory(($this->services['bitbag_sylius_cms_plugin.factory.section'] ?? $this->services['bitbag_sylius_cms_plugin.factory.section'] = new \Sylius\Component\Resource\Factory\Factory('BitBag\\SyliusCmsPlugin\\Entity\\Section')), ($this->services['bitbag_sylius_cms_plugin.factory.section_translation'] ?? $this->services['bitbag_sylius_cms_plugin.factory.section_translation'] = new \Sylius\Component\Resource\Factory\Factory('BitBag\\SyliusCmsPlugin\\Entity\\SectionTranslation')), $a)));
$instance->addFixture(new \BitBag\SyliusCmsPlugin\Fixture\MediaFixture(new \BitBag\SyliusCmsPlugin\Fixture\Factory\MediaFixtureFactory(($this->services['bitbag_sylius_cms_plugin.factory.media'] ?? $this->services['bitbag_sylius_cms_plugin.factory.media'] = new \Sylius\Component\Resource\Factory\Factory('BitBag\\SyliusCmsPlugin\\Entity\\Media')), ($this->services['bitbag_sylius_cms_plugin.factory.media_translation'] ?? $this->services['bitbag_sylius_cms_plugin.factory.media_translation'] = new \Sylius\Component\Resource\Factory\Factory('BitBag\\SyliusCmsPlugin\\Entity\\MediaTranslation')), $c, ($this->services['bitbag_sylius_cms_plugin.resolver.media_provider'] ?? $this->getBitbagSyliusCmsPlugin_Resolver_MediaProviderService()), ($this->services['bitbag_sylius_cms_plugin.repository.media'] ?? $this->getBitbagSyliusCmsPlugin_Repository_MediaService()), ($this->privates['bitbag_sylius_cms_plugin.assigner.products'] ?? $this->load('getBitbagSyliusCmsPlugin_Assigner_ProductsService.php')), ($this->privates['bitbag_sylius_cms_plugin.assigner.sections'] ?? $this->load('getBitbagSyliusCmsPlugin_Assigner_SectionsService.php')))));
$instance->addFixture(($this->services['sylius.fixture.locale'] ?? $this->load('getSylius_Fixture_LocaleService.php')));
$instance->addFixture(($this->services['sylius.fixture.currency'] ?? $this->load('getSylius_Fixture_CurrencyService.php')));
$instance->addFixture(($this->services['sylius.fixture.geographical'] ?? $this->load('getSylius_Fixture_GeographicalService.php')));
$instance->addFixture(($this->services['sylius.fixture.payment_method'] ?? $this->load('getSylius_Fixture_PaymentMethodService.php')));
$instance->addFixture(($this->services['sylius.fixture.shipping_category'] ?? $this->load('getSylius_Fixture_ShippingCategoryService.php')));
$instance->addFixture(($this->services['sylius.fixture.shipping_method'] ?? $this->load('getSylius_Fixture_ShippingMethodService.php')));
$instance->addFixture(($this->services['sylius.fixture.channel'] ?? $this->load('getSylius_Fixture_ChannelService.php')));
$instance->addFixture(($this->services['sylius.fixture.customer_group'] ?? $this->load('getSylius_Fixture_CustomerGroupService.php')));
$instance->addFixture(($this->services['sylius.fixture.shop_user'] ?? $this->load('getSylius_Fixture_ShopUserService.php')));
$instance->addFixture(($this->services['sylius.fixture.admin_user'] ?? $this->load('getSylius_Fixture_AdminUserService.php')));
$instance->addFixture(($this->services['sylius.fixture.product_association_type'] ?? $this->load('getSylius_Fixture_ProductAssociationTypeService.php')));
$instance->addFixture(($this->services['sylius.fixture.product_association'] ?? $this->load('getSylius_Fixture_ProductAssociationService.php')));
$instance->addFixture(($this->services['sylius.fixture.similar_product_association'] ?? $this->load('getSylius_Fixture_SimilarProductAssociationService.php')));
$instance->addFixture(($this->services['sylius.fixture.product_option'] ?? $this->load('getSylius_Fixture_ProductOptionService.php')));
$instance->addFixture(($this->services['sylius.fixture.product_attribute'] ?? $this->load('getSylius_Fixture_ProductAttributeService.php')));
$instance->addFixture(($this->services['sylius.fixture.product_review'] ?? $this->load('getSylius_Fixture_ProductReviewService.php')));
$instance->addFixture(($this->services['sylius.fixture.tax_category'] ?? $this->load('getSylius_Fixture_TaxCategoryService.php')));
$instance->addFixture(($this->services['sylius.fixture.tax_rate'] ?? $this->load('getSylius_Fixture_TaxRateService.php')));
$instance->addFixture(($this->services['sylius.fixture.promotion'] ?? $this->load('getSylius_Fixture_PromotionService.php')));
$instance->addFixture(($this->services['sylius.fixture.taxon'] ?? $this->load('getSylius_Fixture_TaxonService.php')));
$instance->addFixture(($this->services['sylius.fixture.product'] ?? $this->load('getSylius_Fixture_ProductService.php')));
$instance->addFixture(($this->services['sylius.fixture.mug_product'] ?? $this->load('getSylius_Fixture_MugProductService.php')));
$instance->addFixture(($this->services['sylius.fixture.sticker_product'] ?? $this->load('getSylius_Fixture_StickerProductService.php')));
$instance->addFixture(($this->services['sylius.fixture.book_product'] ?? $this->load('getSylius_Fixture_BookProductService.php')));
$instance->addFixture(($this->services['sylius.fixture.tshirt_product'] ?? $this->load('getSylius_Fixture_TshirtProductService.php')));
$instance->addFixture(($this->services['sylius.fixture.order'] ?? $this->load('getSylius_Fixture_OrderService.php')));
$instance->addFixture(($this->services['sylius.fixture.address'] ?? $this->load('getSylius_Fixture_AddressService.php')));
$instance->addFixture(($this->services['sylius.fixture.api_client'] ?? $this->load('getSylius_Fixture_ApiClientService.php')));
$instance->addFixture(($this->services['sylius.fixture.api_access_token'] ?? $this->load('getSylius_Fixture_ApiAccessTokenService.php')));

return $instance;
