<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.fixture.example_factory.payment_method' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/ExampleFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/AbstractExampleFactory.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/PaymentMethodExampleFactory.php';

return $this->services['sylius.fixture.example_factory.payment_method'] = new \Sylius\Bundle\CoreBundle\Fixture\Factory\PaymentMethodExampleFactory(($this->services['sylius.factory.payment_method'] ?? $this->load('getSylius_Factory_PaymentMethodService.php')), ($this->services['sylius.repository.locale'] ?? $this->load('getSylius_Repository_LocaleService.php')), ($this->services['sylius.repository.channel'] ?? $this->getSylius_Repository_ChannelService()));
