<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.listener.checkout_redirect' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Checkout/CheckoutRedirectListener.php';

return $this->privates['sylius.listener.checkout_redirect'] = new \Sylius\Bundle\CoreBundle\Checkout\CheckoutRedirectListener(($this->services['request_stack'] ?? $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()), ($this->privates['sylius.router.checkout_state'] ?? $this->getSylius_Router_CheckoutStateService()), new \Symfony\Component\HttpFoundation\RequestMatcher('/checkout/.+'));
