<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.controller.update_product_taxon_position' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/AdminApiBundle/Controller/ProductTaxonPositionController.php';

return $this->services['sylius.controller.update_product_taxon_position'] = new \Sylius\Bundle\AdminApiBundle\Controller\ProductTaxonPositionController(($this->services['sylius.repository.product_taxon'] ?? $this->load('getSylius_Repository_ProductTaxonService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
