<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.fixture.example_factory.shipping_method' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/ExampleFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/AbstractExampleFactory.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/ShippingMethodExampleFactory.php';

return $this->services['sylius.fixture.example_factory.shipping_method'] = new \Sylius\Bundle\CoreBundle\Fixture\Factory\ShippingMethodExampleFactory(($this->services['sylius.factory.shipping_method'] ?? $this->load('getSylius_Factory_ShippingMethodService.php')), ($this->services['sylius.repository.zone'] ?? $this->getSylius_Repository_ZoneService()), ($this->services['sylius.repository.shipping_category'] ?? $this->load('getSylius_Repository_ShippingCategoryService.php')), ($this->services['sylius.repository.locale'] ?? $this->load('getSylius_Repository_LocaleService.php')), ($this->services['sylius.repository.channel'] ?? $this->getSylius_Repository_ChannelService()));
