<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.listener.user_impersonated' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/EventListener/UserImpersonatedListener.php';

return $this->services['sylius.listener.user_impersonated'] = new \Sylius\Bundle\ShopBundle\EventListener\UserImpersonatedListener(($this->services['sylius.storage.cart_session'] ?? $this->getSylius_Storage_CartSessionService()), ($this->services['sylius.context.channel'] ?? $this->getSylius_Context_ChannelService()), ($this->services['sylius.repository.order'] ?? $this->getSylius_Repository_OrderService()));
