<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius_fixtures.fixture_loader' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/FixturesBundle/Loader/FixtureLoaderInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/FixturesBundle/Loader/HookableFixtureLoader.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/FixturesBundle/Loader/FixtureLoader.php';

return $this->services['sylius_fixtures.fixture_loader'] = new \Sylius\Bundle\FixturesBundle\Loader\HookableFixtureLoader(new \Sylius\Bundle\FixturesBundle\Loader\FixtureLoader());
