<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.controller.sitemap_index' shared service.

include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Controller/SitemapIndexController.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Renderer/SitemapRendererInterface.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Renderer/SitemapRenderer.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Renderer/RendererAdapterInterface.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Renderer/TwigAdapter.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Builder/BuilderInterface.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Builder/SitemapIndexBuilderInterface.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Builder/SitemapIndexBuilder.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Factory/SitemapIndexFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Factory/SitemapIndexFactory.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Provider/IndexUrlProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Provider/IndexUrlProvider.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Factory/SitemapIndexUrlFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/stefandoorn/sitemap-plugin/src/Factory/SitemapIndexUrlFactory.php';

$a = new \SitemapPlugin\Builder\SitemapIndexBuilder(new \SitemapPlugin\Factory\SitemapIndexFactory());
$a->addProvider(($this->privates['bitbag_sylius_cms_plugin.sitemap_provider.page'] ?? $this->load('getBitbagSyliusCmsPlugin_SitemapProvider_PageService.php')));
$a->addProvider(($this->privates['bitbag_sylius_cms_plugin.sitemap_provider.section'] ?? $this->load('getBitbagSyliusCmsPlugin_SitemapProvider_SectionService.php')));
$a->addProvider(($this->privates['sylius.sitemap_provider.product'] ?? $this->load('getSylius_SitemapProvider_ProductService.php')));
$a->addProvider(($this->privates['sylius.sitemap_provider.taxon'] ?? $this->load('getSylius_SitemapProvider_TaxonService.php')));
$a->addProvider(($this->privates['sylius.sitemap_provider.static'] ?? $this->load('getSylius_SitemapProvider_StaticService.php')));
$a->addIndexProvider(new \SitemapPlugin\Provider\IndexUrlProvider(($this->services['router'] ?? $this->getRouterService()), new \SitemapPlugin\Factory\SitemapIndexUrlFactory()));

return $this->services['sylius.controller.sitemap_index'] = new \SitemapPlugin\Controller\SitemapIndexController(new \SitemapPlugin\Renderer\SitemapRenderer(new \SitemapPlugin\Renderer\TwigAdapter(($this->services['templating'] ?? $this->getTemplatingService()), '@SitemapPlugin/index.xml.twig', true)), $a);
