<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.customer_statistics_provider' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Core/Customer/Statistics/CustomerStatisticsProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Core/Customer/Statistics/CustomerStatisticsProvider.php';

return $this->services['sylius.customer_statistics_provider'] = new \Sylius\Component\Core\Customer\Statistics\CustomerStatisticsProvider(($this->services['sylius.repository.order'] ?? $this->getSylius_Repository_OrderService()), ($this->services['sylius.repository.channel'] ?? $this->getSylius_Repository_ChannelService()));
