<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.order_processing.order_promotion_processor' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Order/Processor/OrderProcessorInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Component/Core/OrderProcessing/OrderPromotionProcessor.php';

return $this->services['sylius.order_processing.order_promotion_processor'] = new \Sylius\Component\Core\OrderProcessing\OrderPromotionProcessor(($this->services['sylius.promotion_processor'] ?? $this->load('getSylius_PromotionProcessorService.php')));
