<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.email_manager.order' shared service.

include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/EmailManager/OrderEmailManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/EmailManager/OrderEmailManager.php';

return $this->services['sylius.email_manager.order'] = new \Sylius\Bundle\ShopBundle\EmailManager\OrderEmailManager(($this->services['sylius.email_sender'] ?? $this->load('getSylius_EmailSenderService.php')));
